name: AppInspect
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "develop"
  
jobs:

  # Package App
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # semantic-release won't trigger a tagged build if this is not set false
          persist-credentials: false

      - name: Package Splunk App with CLI
        run: |
          pwd
          ls -la
          cd ${GITHUB_WORKSPACE}
          mv package TA-trustedx
          mkdir dist
          tar -zcvf dist/TA-trustedx.tar.gz TA-trustedx
          cd dist
          ls -la
          pwd

      - name: Upload package as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: package-splunkbase
          path: /home/runner/work/TA-trustedx/TA-trustedx/dist
        if: always()

  # Run AppInspect CLI
  appinspect-cli:
    name: AppInspect CLI
    needs: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          - "cloud"
          - "appapproval"
          - "deprecated_feature"
          - "developer_guidance"
          - "future"
          - "self-service"
          - "splunk_appinspect"
    steps:
      - name: Get AppInspect CLI
        uses: actions/download-artifact@v2
        with:
          name: package-splunkbase
          path: dist

      - name: Run AppInspect CLI
        uses: splunk/appinspect-cli-action@v1.3.0
        with:
          app_path: dist
          included_tags: ${{ matrix.tags }}