name: Publish to Splunkbase
on: workflow_dispatch

jobs:

  splunkbase-release:
    name: Splunkbase release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # semantic-release won't trigger a tagged build if this is not set false
          persist-credentials: false

      - name: Load ENV variables
        id: vars
        run: |
          source .splunkbase
          echo ::set-output name=SPLUNKBASE_ID::"$SPLUNKBASE_ID"
          echo ::set-output name=SPLUNKBASE_SPLUNK_VERSION::"$SPLUNKBASE_SPLUNK_VERSION"
          echo ::set-output name=SPLUNKBASE_SPLUNK_CIM_VERSION::"$SPLUNKBASE_SPLUNK_CIM_VERSION"

      - name: Package Splunk App with CLI
        run: |
          pwd
          ls -la
          cd ${GITHUB_WORKSPACE}
          mv package TA-trustedx
          mkdir dist
          tar -zcvf dist/TA-trustedx.tgz TA-trustedx
          cd dist
          ls -la
          pwd
          
      - name: Publish to Splunkbase
        shell: bash
        run: |
          cd /home/runner/work/TA-trustedx/TA-trustedx/dist
          pwd
          ls
          curl -u ${{ secrets.SPLUNKBASE_USER }}:${{ secrets.SPLUNKBASE_PASSWORD }} --request POST https://splunkbase.splunk.com/api/v1/app/${{ steps.vars.outputs.SPLUNKBASE_ID }}/new_release/ -F "files[]=@/home/runner/work/TA-ibm_secretserver/TA-ibm_secretserver/dist/TA-ibm_secretserver.tgz" -F "filename=TA-ibm_secretserver.tgz" -F "cim_versions=${{ steps.vars.outputs.SPLUNKBASE_SPLUNK_CIM_VERSION }}" -F "splunk_versions=${{ steps.vars.outputs.SPLUNKBASE_SPLUNK_VERSION }}" -F "visibility=true"

        
      